Creating new plugin tutorial
membraneframework/membrane_tutorials pull request #19
Opened 2022-03-22 12:35 UTC by shuntrho

Added short guide on creating new Membrane plugin.

2022-03-23 07:30 UTC, varsill requested changes
Great, that's what we had on our mind! :D 
Just these two fixes concerning the grammar are required

2022-03-23 07:30 UTC, varsill commented on create_new_plugin/create_new_plugin.md
> +In order to create new plugin we recommended using the [template](https://github.com/membraneframework/membrane_template_plugin) which has been made for this very purpose and which will be the base o
```suggestion
In order to create a new plugin, we recommend using the [template](https://github.com/membraneframework/membrane_template_plugin) which has been made for this very purpose and which will be the base of your plugin.
```

2022-03-23 07:30 UTC, varsill commented on create_new_plugin/create_new_plugin.md
> +During the development of Membrane Framework we aim at designing fewer, but higher quality plugins. However we also kept extendability and reusability in mind. That's why it is easy for developers li
```suggestion
During the development of Membrane Framework we aim at designing fewer, but higher quality plugins. However, we also kept extendability and reusability in mind. That's why it is easy for developers like you to create their own custom plugin, which satisfies their needs.
```

2022-03-25 07:35 UTC, varsill approved these changes
LGTM! 🥇

2022-03-25 12:02 UTC, merged

2022-03-28 06:21 UTC, varsill commented
We should think if it would be good to add a link to the new tutorial in the README.md here and there: https://github.com/membraneframework/membraneframework.github.io/blob/master/index.md
therefore making it public

2022-03-28 10:07 UTC, shuntrho commented
I wonder if it should be added in the plugin repo as well. https://github.com/membraneframework/membrane_template_plugin

2022-03-28 11:33 UTC, varsill commented
Hmm, as far as I know, when repo is marked as a template, it should contain only necessary stuff as it will be available in somebody's project - we cannot separate the readme out of the template :/ 
Another thing is that we should finally make template public