Add RN tutorial
membraneframework/membrane_tutorials pull request #44
Opened 2022-09-09 07:23 UTC by blazpie

2022-09-12 12:04 UTC, varsill commented on react_native_webrtc/02_preparations.md
> +Next, add it to `plugins` in `App.json`:
```suggestion
Next, add it to `plugins` in `app.json`:
```

2022-09-12 12:04 UTC, varsill commented on react_native_webrtc/02_preparations.md
> +expo prebuild
While running that command, I was asked: 
```
What would you like your Android package name to be? ...
```
I couldn't provide a name which would satisfy the naming convention (and apart from the `Wrong package name` error print no information was provided about the naming convention). Finally, I have found out, that the name should consist of two parts, divided wit a dot (something like: `<first_part>.<second_part>`). Perhaps it is obvious for Expo developers, but for me it was a problem - I would suggestion mentioning that here in the tutorial, or linking a comprehensive Expo setup tutorial which would cover that the naming convention on top of this chapter.

2022-09-14 12:35 UTC, DominikWolek commented on react_native_webrtc/02_preparations.md
> +create-expo-app membrane_rn_webrtc_demo
+1

2022-11-15 15:33 UTC, jerzywilczek requested changes

2024-03-28 10:38 UTC, closed without merging