Broadcasting tutorial
membraneframework/membrane_tutorials pull request #49
Opened 2022-09-20 10:24 UTC by varsill

This PR adds the broadcasting tutorial, which consists of two parts:
* RTMP to HLS tutorial
* RTSP to HLS tutorial

2022-09-20 14:06 UTC, shuntrho approved these changes
LGTM

2022-09-22 14:17 UTC, blazpie commented on broadcasting/index.md
> +graphicPath: ../assets/images/Illo_fallback.png
nope. Leave it empty here. A site should fallback to default image if a field is empty or absent.

2022-10-12 12:02 UTC, blazpie requested changes
Please remove folder assets that contains fallback image. It's way easier to fallback from static image in www code.

2022-10-13 11:12 UTC, blazpie approved these changes

2022-10-13 14:14 UTC, merged